baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = 'anatole'

[params]
  title = "OSDC"
  readMore = true
  profilePicture = "images/osdc.png"
  description = "Open Source Development Cooking"
  customCss = ["css/custom.css"]

