baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'OSDContenst'

theme = 'anatole'

[params]
  title = "OSDContenst"
  readMore = true
  profilePicture = "images/osdc.png"
  description = "A Content Writing Contest"
  customCss = ["css/custom.css"]

